In [1]:
import torch
import numpy as np

In [2]:
x = torch.arange(6).reshape(3,2)

In [3]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [5]:
type(x[1,1])

torch.Tensor

In [8]:
x[:,1]

tensor([1, 3, 5])

In [9]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [10]:
x = torch.arange(10)

In [11]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [13]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
x = x.reshape(2,5)

In [17]:
x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [18]:
x = torch.arange(10)

In [19]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
x.shape

torch.Size([10])

In [22]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [23]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
z = x.view(2,5)

In [25]:
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [26]:
x[0] = 9999

In [27]:
x

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [28]:
z

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [29]:
x = torch.arange(10)

In [30]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
x.shape

torch.Size([10])

In [32]:
# will INFER what the 2nd dimention is
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [33]:
x.view(-1,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [34]:
a = torch.tensor([1.,2.,3.])

In [35]:
b = torch.tensor([4.,5.,6.])

In [36]:
a

tensor([1., 2., 3.])

In [37]:
b

tensor([4., 5., 6.])

In [38]:
a.dtype

torch.float32

In [39]:
a + b

tensor([5., 7., 9.])

In [40]:
torch.add(a,b)

tensor([5., 7., 9.])

In [41]:
a.mul(b)

# a = a + b

tensor([ 4., 10., 18.])

In [42]:
a

tensor([1., 2., 3.])

In [43]:
a.mul_(b)

tensor([ 4., 10., 18.])

In [44]:
a

tensor([ 4., 10., 18.])

In [45]:
a = torch.tensor([1.,2.,3.])

In [46]:
a

tensor([1., 2., 3.])

In [47]:
b

tensor([4., 5., 6.])

In [48]:
a * b

tensor([ 4., 10., 18.])

In [49]:
a.mul(b)

tensor([ 4., 10., 18.])

In [50]:
a.dot(b)

tensor(32.)

In [51]:
a = torch.tensor([[0,2,4],[1,3,5]])

In [52]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [53]:
b = torch.tensor([[6,7],[8,9],[10,11]])

In [54]:
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [55]:
a.shape

torch.Size([2, 3])

In [56]:
b.shape

torch.Size([3, 2])

In [57]:
torch.mm(a,b)

tensor([[56, 62],
        [80, 89]])

In [58]:
# not really recommended
a @ b

tensor([[56, 62],
        [80, 89]])

In [60]:
x = torch.tensor([2.,3.,4.,5.])

In [61]:
x

tensor([2., 3., 4., 5.])

In [62]:
x.norm()

tensor(7.3485)

In [63]:
x.numel()

4

In [64]:
len(x)

4

In [65]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [66]:
len(a)

2

In [67]:
a.numel()

6