# Part 1

In [1]:
import torch

In [2]:
import numpy as np

In [3]:
torch.__version__

'1.10.2+cu102'

In [4]:
arr = np.array([1,2,3,4,5])

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
arr.dtype

dtype('int32')

In [7]:
type(arr)

numpy.ndarray

In [9]:
x = torch.from_numpy(arr)

In [10]:
type(x)

torch.Tensor

In [ ]:
# same as in/out[9]

In [11]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [12]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [13]:
x.dtype

torch.int32

In [14]:
arr_2d = np.arange(0.0,12.0) 

In [16]:
arr2d = arr_2d.reshape(4,3)

In [17]:
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [18]:
x2 = torch.from_numpy(arr2d)

In [19]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [20]:
arr

array([1, 2, 3, 4, 5])

In [21]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [22]:
arr[0] = 99

In [23]:
arr

array([99,  2,  3,  4,  5])

In [24]:
x

tensor([99,  2,  3,  4,  5], dtype=torch.int32)

In [27]:
my_arr = np.arange(0,10)

In [28]:
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
my_tensor = torch.tensor(my_arr)

In [30]:
my_other_tensor = torch.from_numpy(my_arr)

In [31]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [32]:
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [33]:
my_arr[0] = 99

In [34]:
my_arr

array([99,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [35]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [36]:
my_other_tensor

tensor([99,  1,  2,  3,  4,  5,  6,  7,  8,  9], dtype=torch.int32)

# Part two

In [37]:
new_arr = np.array([1,2,3])

In [38]:
new_arr.dtype

dtype('int32')

In [39]:
torch.tensor(new_arr)

tensor([1, 2, 3], dtype=torch.int32)

In [41]:
my_tensor = torch.Tensor(new_arr)

In [42]:
my_tensor.dtype

torch.float32

In [45]:
torch.empty(4,2)

tensor([[0.0000e+00, 0.0000e+00],
        [1.8754e+28, 8.0439e+20],
        [6.9060e-07, 1.3029e-11],
        [1.7186e-04, 2.7150e-06]])

In [50]:
torch.zeros(4,3,dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [51]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [53]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [55]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [56]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [57]:
my_tensor = torch.tensor([1,2,3])

In [58]:
my_tensor.dtype

torch.int64

In [60]:
my_tensor = my_tensor.type(torch.int32)

In [61]:
my_tensor.dtype

torch.int32

In [62]:
torch.rand(4,3)

tensor([[0.1965, 0.0326, 0.1923],
        [0.8310, 0.5926, 0.9984],
        [0.2247, 0.2616, 0.8148],
        [0.6781, 0.2582, 0.7449]])

In [63]:
torch.randn(4,3)

tensor([[-1.5480, -0.0798, -0.6527],
        [ 2.5538, -0.1881,  0.2707],
        [-1.0986, -1.1476,  0.0847],
        [-0.0396,  0.3504,  0.0262]])

In [64]:
torch.randint(0,10,(5,5))

tensor([[8, 1, 3, 7, 0],
        [3, 2, 6, 2, 7],
        [7, 5, 2, 7, 6],
        [9, 6, 4, 4, 8],
        [1, 1, 2, 4, 5]])

In [65]:
x = torch.zeros(2,5)

In [66]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [67]:
torch.rand_like(x)

tensor([[0.5787, 0.5265, 0.7780, 0.6093, 0.1764],
        [0.7962, 0.4091, 0.1750, 0.6149, 0.7638]])

In [69]:
torch.randn_like(x)

tensor([[-1.0029,  0.6026, -1.7321, -2.0270,  1.4325],
        [-1.0804,  1.0039,  0.1347,  1.2192, -0.0303]])

In [70]:
torch.randint_like(x,0,10)

tensor([[1., 7., 5., 1., 2.],
        [0., 1., 7., 4., 9.]])

In [71]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [72]:
torch.rand(2,3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [73]:
torch.rand(2,3)

tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])