In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [11]:
new_arr = arr / 2

In [12]:
new_arr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

# Broadcasting of a reassignment

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
slice_arr = arr[0:6]

In [18]:
slice_arr

array([0, 1, 2, 3, 4, 5])

In [20]:
slice_arr[:] = 99

In [21]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [22]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
arr_copy = arr.copy()

In [25]:
arr_copy[:] = 1000

In [26]:
arr_copy

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [27]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# Indexing on a 2D array

In [30]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [31]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [32]:
arr_2d.shape

(3, 3)

In [34]:
arr_2d[1][1]

25

In [35]:
arr_2d[1,1]

25

In [36]:
arr_2d[2,2]

45

In [41]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

# Conditional selection

In [44]:
arr = np.arange(1,11)

In [45]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [47]:
bool_arr = arr > 4

In [48]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [49]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [50]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [51]:
arr[arr <= 6]

array([1, 2, 3, 4, 5, 6])